# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agena < Formula
  desc "Official CLI for the AGENA platform"
  homepage "https://agena.dev"
  version "1.1.0"
  license "MIT"

  depends_on "node" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aozyildirim/Agena/releases/download/v1.1.0/agena_1.1.0_darwin_amd64.tar.gz"
      sha256 "cb5e279d0861e9e1bce201ebef1e530f43d702e45b76593065d2d83fba5d4d71"

      define_method(:install) do
        bin.install "agena"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aozyildirim/Agena/releases/download/v1.1.0/agena_1.1.0_darwin_arm64.tar.gz"
      sha256 "0bcc1cb5d7ae855b03ad084b642379989ef039374fd0746f403ee097693dd4d3"

      define_method(:install) do
        bin.install "agena"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aozyildirim/Agena/releases/download/v1.1.0/agena_1.1.0_linux_amd64.tar.gz"
      sha256 "f26186d07ef829bca16bbe807756181186c8ea3b509dbad689631e2b39e8af64"
      define_method(:install) do
        bin.install "agena"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aozyildirim/Agena/releases/download/v1.1.0/agena_1.1.0_linux_arm64.tar.gz"
      sha256 "4fa8921d3dc8eb5f5bc7127b7e06e28cb83f139130251b1a7e6fe39991daf7b2"
      define_method(:install) do
        bin.install "agena"
      end
    end
  end

  def caveats
    <<~EOS
      For the full command set while the Go port is in progress, also run:

          npm install -g @agena/cli

      Once Go-native parity lands the npm dependency will go away.
    EOS
  end
end
