# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agena < Formula
  desc "Official CLI for the AGENA platform"
  homepage "https://agena.dev"
  version "1.1.4"
  license "MIT"

  depends_on "node" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aozyildirim/Agena/releases/download/v1.1.4/agena_1.1.4_darwin_amd64.tar.gz"
      sha256 "edbdabb7f9dfee8545ef722c698daceb5cc2cab260f7e10d45a5ce6666a61a8a"

      define_method(:install) do
        bin.install "agena"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aozyildirim/Agena/releases/download/v1.1.4/agena_1.1.4_darwin_arm64.tar.gz"
      sha256 "ba4d1bbb4af50f10157ceb74811badb47a37ebffa7161778f937049596727a0f"

      define_method(:install) do
        bin.install "agena"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aozyildirim/Agena/releases/download/v1.1.4/agena_1.1.4_linux_amd64.tar.gz"
      sha256 "338f4f14cfcfd5ac0dc477b139a3bdaeca8d151b386664fb78dbeb6bc51391a7"
      define_method(:install) do
        bin.install "agena"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aozyildirim/Agena/releases/download/v1.1.4/agena_1.1.4_linux_arm64.tar.gz"
      sha256 "01b15566fe592e7452dd39d01d62dc0cdddf57259dc7eb7c5baf0557eef46078"
      define_method(:install) do
        bin.install "agena"
      end
    end
  end

  def caveats
    <<~EOS
      For the full command set while the Go port is in progress, also run:

          npm install -g @agenaai/cli

      Once Go-native parity lands the npm dependency will go away.
    EOS
  end
end
