# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agena < Formula
  desc "Official CLI for the AGENA platform"
  homepage "https://agena.dev"
  version "1.2.1"
  license "MIT"

  depends_on "node" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aozyildirim/Agena/releases/download/v1.2.1/agena_1.2.1_darwin_amd64.tar.gz"
      sha256 "fc29a9a4a5b852c40715730dc1841ad20c1860d420674450d9a26664fa196a89"

      define_method(:install) do
        bin.install "agena"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aozyildirim/Agena/releases/download/v1.2.1/agena_1.2.1_darwin_arm64.tar.gz"
      sha256 "d6b03043bc0ea5a775f2f28bfac1f8d4131db0207d1bd3a1e3c7fb1c332ee1ec"

      define_method(:install) do
        bin.install "agena"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aozyildirim/Agena/releases/download/v1.2.1/agena_1.2.1_linux_amd64.tar.gz"
      sha256 "bc1a13abd6fabbc1b4e1ed6af873159ecf5465d57df282390fec6e39b25c1f05"
      define_method(:install) do
        bin.install "agena"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aozyildirim/Agena/releases/download/v1.2.1/agena_1.2.1_linux_arm64.tar.gz"
      sha256 "99cf8df9100837db56d58de6e3189487d888c477639bc56ecf26c727d09dd79d"
      define_method(:install) do
        bin.install "agena"
      end
    end
  end

  def caveats
    <<~EOS
      For the full command set while the Go port is in progress, also run:

          npm install -g @agenaai/cli

      Once Go-native parity lands the npm dependency will go away.
    EOS
  end
end
