# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agena < Formula
  desc "Official CLI for the AGENA platform"
  homepage "https://agena.dev"
  version "1.3.1"
  license "MIT"

  depends_on "node" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aozyildirim/Agena/releases/download/v1.3.1/agena_1.3.1_darwin_amd64.tar.gz"
      sha256 "2bae1e2632d6c0de8d7acc153f795652d3e08378ee0ebb0f938bc0d9c3d34411"

      define_method(:install) do
        bin.install "agena"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aozyildirim/Agena/releases/download/v1.3.1/agena_1.3.1_darwin_arm64.tar.gz"
      sha256 "151139a21daa48f76256f7855493a7eff49ba4933b3ef76da8be2c768df2b30f"

      define_method(:install) do
        bin.install "agena"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aozyildirim/Agena/releases/download/v1.3.1/agena_1.3.1_linux_amd64.tar.gz"
      sha256 "a0324bc78963489febe83dae2b5d2ee79a45eed77f507fc6bad4e4e0d0f3085a"
      define_method(:install) do
        bin.install "agena"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aozyildirim/Agena/releases/download/v1.3.1/agena_1.3.1_linux_arm64.tar.gz"
      sha256 "d17056b102b52e0a57e37090a4a0238c12b68f28bf8f472d1cd3784eaad7e340"
      define_method(:install) do
        bin.install "agena"
      end
    end
  end

  def caveats
    <<~EOS
      For the full command set while the Go port is in progress, also run:

          npm install -g @agenaai/cli

      Once Go-native parity lands the npm dependency will go away.
    EOS
  end
end
